#Enable tracking pointer
Available = true
#The style of the pointer
#Allowed Values: CENTER_RELATIVE, HEAD_FLAT, TRACK_FULL
mappingStyle = "CENTER_RELATIVE"
#The algorithm of the projection
#Allowed Values: MERCATOR, AITOFF, WINKEL_TRIPLE
projectAlgorithm = "AITOFF"
#List of entity types with cursors, separated with "|"
"entityTypes|Pointer|EntityIcon" = ["minecraft:ender_dragon|normal_red|ender_dragon_head", "minecraft:wither|normal_white|wither_head", "terra_entity:king_slime|normal_red|king_slime", "terra_entity:eye_of_cthulhu|normal_red|eye_of_cthulhu", "terra_entity:brain_of_cthulhu|normal_red|brain_of_cthulhu", "terra_entity:eater_of_worlds|normal_red|eater_of_worlds", "terra_entity:queen_bee|normal_red|queen_bee", "terra_entity:skeletron|normal_red|skeletron"]
