[general]
	#List of waystone origins that should prevent others from editing. PLAYER is special in that it allows only edits by the owner of the waystone.
	restrictedWaystones = ["PLAYER", "UNKNOWN", "VILLAGE", "WILDERNESS", "DUNGEON"]
	#Set to "GLOBAL" to have newly placed or found waystones be global by default.
	#Allowed Values: ACTIVATION, GLOBAL, SHARD_ONLY, ORANGE_SHARESTONE, MAGENTA_SHARESTONE, LIGHT_BLUE_SHARESTONE, YELLOW_SHARESTONE, LIME_SHARESTONE, PINK_SHARESTONE, GRAY_SHARESTONE, LIGHT_GRAY_SHARESTONE, CYAN_SHARESTONE, PURPLE_SHARESTONE, BLUE_SHARESTONE, BROWN_SHARESTONE, GREEN_SHARESTONE, RED_SHARESTONE, BLACK_SHARESTONE
	defaultVisibility = "ACTIVATION"
	#Add "GLOBAL" to allow every player to create global waystones.
	allowedVisibilities = []
	#The time in ticks that it takes to use a warp stone. This is the charge-up time when holding right-click.
	warpStoneUseTime = 60
	#The time in ticks that it takes to use a warp plate. This is the time the player has to stand on top for.
	warpPlateUseTime = 20
	#The time in ticks it takes to use a scroll. This is the charge-up time when holding right-click.
	scrollUseTime = 60

[inventoryButton]
	#Set to 'NONE' for no inventory button. Set to 'NEAREST' for an inventory button that teleports to the nearest waystone. Set to 'ANY' for an inventory button that opens the waystone selection menu. Set to a waystone name for an inventory button that teleports to a specifically named waystone.
	inventoryButton = ""
	#The x position of the inventory button in the inventory.
	inventoryButtonX = 58
	#The y position of the inventory button in the inventory.
	inventoryButtonY = 60
	#The y position of the inventory button in the creative menu.
	creativeInventoryButtonX = 88
	#The y position of the inventory button in the creative menu.
	creativeInventoryButtonY = 33

[worldGen]
	#Set to 'DEFAULT' to only generate the normally textured waystones. Set to 'MOSSY' or 'SANDY' to generate all as that variant. Set to 'BIOME' to make the style depend on the biome it is generated in.
	#Allowed Values: DEFAULT, MOSSY, SANDY, BLACKSTONE, DEEPSLATE, END_STONE, BIOME
	wildWaystoneStyle = "BIOME"
	#Approximate chunk distance between wild waystones being generated. Set to 0 to disable generation.
	chunksBetweenWildWaystones = 0
	#List of dimensions that wild waystones are allowed to spawn in. If left empty, all dimensions except those in wildWaystonesDimensionDenyList are used.
	wildWaystonesDimensionAllowList = ["minecraft:overworld", "minecraft:the_end", "minecraft:the_nether"]
	#List of dimensions that wild waystones are not allowed to spawn in. Only used if wildWaystonesDimensionAllowList is empty.
	wildWaystonesDimensionDenyList = []
	#Set to 'PRESET_FIRST' to first use names from the nameGenerationPresets. Set to 'PRESET_ONLY' to use only those custom names. Set to 'MIXED' to have some waystones use custom names, and others random names.
	#Allowed Values: PRESET_FIRST, RANDOM_ONLY, PRESET_ONLY, MIXED
	nameGenerationMode = "PRESET_FIRST"
	#The template to use when generating new names. Supported placeholders are {Biome} (english biome name) and {MrPork} (the default name generator).
	nameGenerationTemplate = "{MrPork}"
	#These names will be used for the PRESET name generation mode. See the nameGenerationMode option for more info.
	nameGenerationPresets = ["Todd", "Home Depot", "Costco", "Red Lobster", "Darkest Armpit", "Dankington", "What Is Love?", "Dunkin Donuts", "Blockbuster Video", "Look Behind You", "jk roflmao", "Here", "There", "Over Yonder", "Taco Palace", "Updog", "House of 1000 Snakes", "There Here Is A Waystone", "High Fives", "Descent Into Madness", "Winner Winner Chicken Dinner", "Cybertron", "Cobra Kai Dojo", "Run's House", "Chuck E. Cheese", "Somewhere", "Hopeulikit", "Sponsored by Nvidia", "Flarb", "Grungingham", "Potato Town", "SCREEE", "#2", "#waystone", "Mambo No. 5", "Welcome to Chili's", "Thanks! I Hate It", "Live. Laugh. Love.", "Dollar General", "OU812", "Minceraft", "lolwut", "3.14159", "Pork Chop Sandwiches", "Body Massage", "These Uncertain Times", "The Trailer Park", "Church of Chungus", "Herobrine's Hallway", "Bedrock Edition", "That's No Moon!", "House of Sleep", "Lonk's Loft", "It's A Trap!", "Helm's Deep", "You Are Here", "glhf", "TBD", "NYI", "Jurassic Parking Lot", "Self-Isolation", "It's Been One Week", "Amish Paradise", "Zeldo's Perch", "Ganondork's Gazebo", "Mom's Spaghetti", "Lebowski Lookout", "Another Dumb Waystone Name", "I CAN SEE FOREVER", "HIP HOP!", "Hexxit Is Better", "Shoggoth's Shake Shack", "Paul's Boutique", "Dante's Inferno", "Curbside Pickup", "Stark Tower", "Krypton", "Cheezers", "The Bacons Are Lit", "The Beacons Are Lit AF", "Gondor Calls For Ayyy", "Gimli's Gravy Boat", "100% Save File", "r/WhereDidTheSodaGo", "GT:NH", "Unlimited Breadsticks", "Now That's What I Call A Waystone!", "42", "ShowBiz Pizza Place", "The Upside Down", "Castle Byers", "Starcourt Mall", "THEY ARE WATCHING", "Flavortown", "Fieri's Gambit", "Wheels on Meals", "Darude's Party Deck", "Are Ya Ready, Kids?", "Pineapple Under The Sea", "AFK", "You Did It", "11/10", "Oderus Overlook", "Alt-F4", "Quint's Downfall", "Amity Bait Shop", "The Chum Bucket", "The Krusty Krab", "Your Mom", "It's Corn", "Seinfeld's Apartment", "This. Is. Sparta.", "Gangsta's Paradise", "Insert Coin", "Close Enough", "Between Two Ferns", "Waaaaaaaystone", "PEANUT BUTTER JELLY TIME", "Run's House", "Grassy Knoll", "Bikini Atoll", "Whey Stone", "Weigh Station", "Jeb's Country Cookin'", "Here Lies W.A. Stone", "Do It Lady!", "Reading Rainbow", "Reading Rambo", "Fyre Fest", "A Warm Place", "A Quiet Place", "East Pines", "Wing Kingdom", "Time Room", "Billy's Cave", "E-I-E-I-O", "B-I-N-G-O", "Bluey's Backyard", "Atlantis Morissette", "The Good Place", "Full House", "Sharon Waystone", "Mayberry", "Low Effort Landing", "Xanadu", "Cursed Durst", "Salem's RV Lot", "Reputable Auto Dealership", "You Just Right-Clicked", "Spirit Halloween", "The Limpest Bizkit", "Tom Nook's Nunnery", "Nic's Cage", "Cypress Hill", "Worcestershire", "Ankh-Morpork", "Internet Archive", "Mr. Rogers' Neighborhood", "The Great Northern Hotel", "Packard Sawmill", "Planet Caravan", "DMV", "Problematic Celebrity Hideout", "Watership Down", "World C-3", "CB4", "Where It's At"]
	#Set to REGULAR to have waystones spawn in some villages. Set to FREQUENT to have waystones spawn in most villages. Set to DISABLED to disable waystone generation in villages. Waystones will only spawn in vanilla or supported villages.
	#Allowed Values: DISABLED, REGULAR, FREQUENT
	spawnInVillages = "REGULAR"

[teleports]
	#Set to false to simply disable all xp costs. See warpRequirements for more fine-grained control.
	enableCosts = true
	#Set to false to simply disable all cooldowns. See warpRequirements for more fine-grained control.
	enableCooldowns = true
	#List of warp requirements with comma-separated parameters in parentheses. Conditions can be defined as comma-separated list in square brackets. Will be applied in order.
	warpRequirements = ["[is_not_interdimensional] scaled_add_xp_cost(distance, 0.01)", "[is_interdimensional] add_xp_cost(27)", "[source_is_warp_plate] multiply_xp_cost(0)", "[target_is_global] multiply_xp_cost(0)", "min_xp_cost(0)", "max_xp_cost(27)", "[source_is_inventory_button] add_cooldown(inventory_button, 300)"]
	#Set to ENABLED to have nearby pets teleport with you. Set to SAME_DIMENSION to have nearby pets teleport with you only if you're not changing dimensions. Set to DISABLED to disable.
	#Allowed Values: ENABLED, SAME_DIMENSION, DISABLED
	transportPets = "DISABLED"
	#Set to ENABLED to have leashed mobs teleport with you. Set to SAME_DIMENSION to have leashed mobs teleport with you only if you're not changing dimensions. Set to DISABLED to disable.
	#Allowed Values: ENABLED, SAME_DIMENSION, DISABLED
	transportLeashed = "ENABLED"
	#List of entities that cannot be teleported, either as pet, leashed, or on warp plates.
	entityDenyList = ["minecraft:wither"]
	#Set to true to enable warp modifier items for applying status effects on teleports.
	enableModifiers = true

[client]
	#If enabled, the text overlay on waystones will no longer always render at full brightness.
	disableTextGlow = false

[compatibility]
	#If enabled, JourneyMap waypoints will be created for each activated waystone.
	journeyMap = true
	#If enabled, JourneyMap waypoints will only be created if the mod 'JourneyMap Integration' is not installed
	preferJourneyMapIntegrationMod = true
	#If enabled, Waystones will add markers for waystones and sharestones to BlueMap.
	blueMap = true
	#If enabled, Waystones will add markers for waystones and sharestones to Dynmap.
	dynmap = true
